# Generated by Django 3.2.23 on 2023-12-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('cardholder_name', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('account_no', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
