# Generated by Django 3.2.23 on 2023-12-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('amount', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
    ]
