# Generated by Django 3.2.23 on 2023-12-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
